### ISSUE TITLE
How to obtain qm9 dataset as .db format.

### ISSUE THREAD

**Issue by huangbinapple** [tensorfieldnetworks/tensorfieldnetworks#4]
In ```missing_point_test.ipynb```, there is qm9.db, as I know, the raw qm9 dataset was public available in *.xyz format, how to convert it into the .db format which used in this script?

**Comment by blondegeek** [comment]
Hi @huangbinapple, 

I believe you can use the file here: 
https://www.dropbox.com/s/abw3iotzoqhpesl/qm9.db.gz?dl=0
(I haven't recently checked it - but it should be the same)

However, I would recommend that if you are interested in Euclidean symmetry equivariant neural networks you head over to https://github.com/e3nn/e3nn and e3nn.org where we have a much more up to date and efficient repository for implementing these types of networks.

Best,
Tess
